# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: books.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'books.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62ooks.proto\x12\x0f\x62ookverse.books\x1a\x1bgoogle/protobuf/empty.proto\"I\n\x04\x42ook\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x16\n\x0epublished_year\x18\x04 \x01(\x05\"\x14\n\x06\x42ookId\x12\n\n\x02id\x18\x01 \x01(\x05\"8\n\x11\x43reateBookRequest\x12#\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x15.bookverse.books.Book\"9\n\x12\x43reateBookResponse\x12#\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x15.bookverse.books.Book\"6\n\x0fGetBookResponse\x12#\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x15.bookverse.books.Book\"9\n\x11ListBooksResponse\x12$\n\x05\x62ooks\x18\x01 \x03(\x0b\x32\x15.bookverse.books.Book2\xed\x01\n\x05\x42ooks\x12U\n\nCreateBook\x12\".bookverse.books.CreateBookRequest\x1a#.bookverse.books.CreateBookResponse\x12\x44\n\x07GetBook\x12\x17.bookverse.books.BookId\x1a .bookverse.books.GetBookResponse\x12G\n\tListBooks\x12\x16.google.protobuf.Empty\x1a\".bookverse.books.ListBooksResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'books_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOK']._serialized_start=61
  _globals['_BOOK']._serialized_end=134
  _globals['_BOOKID']._serialized_start=136
  _globals['_BOOKID']._serialized_end=156
  _globals['_CREATEBOOKREQUEST']._serialized_start=158
  _globals['_CREATEBOOKREQUEST']._serialized_end=214
  _globals['_CREATEBOOKRESPONSE']._serialized_start=216
  _globals['_CREATEBOOKRESPONSE']._serialized_end=273
  _globals['_GETBOOKRESPONSE']._serialized_start=275
  _globals['_GETBOOKRESPONSE']._serialized_end=329
  _globals['_LISTBOOKSRESPONSE']._serialized_start=331
  _globals['_LISTBOOKSRESPONSE']._serialized_end=388
  _globals['_BOOKS']._serialized_start=391
  _globals['_BOOKS']._serialized_end=628
# @@protoc_insertion_point(module_scope)
